### ISSUE TITLE
Proposed enhancement: add support for IO streams as input

### ISSUE THREAD

**Issue by DidierStevens** [GillesArcas/PythonSed#3]
This is a great module, thanks for coding this!

I made a very small change to sed.py method apply (lines 219 and 220):

            if type(source_file) != str:
                self.input_file = source_file

Now I can pass a StringIO as argument to method apply.

I didn't have to make changes for output: IO streams are already supported.

Now I can process text in memory with PythonSed, without having to create files.

Tested with Python 2.7 and 3.7.

I didn't create a PR, as I assumed you might want to code this differently (not use a type check).

Thanks for your work!

**Comment by GillesArcas** [comment]
Hi Dider,
nice improvement. I don't care too much about using type(). Make a PR if you wish or I can make the modification. Just tell me.
Gilles

**Comment by DidierStevens** [comment]
Thanks Gilles!

I'll make a PR.

Cheers,

Didier

**Comment by DidierStevens** [comment]
PR created.
