### ISSUE TITLE
Not processing correctly for \> at the end of the line.

### ISSUE THREAD

**Issue by sptitzer1** [GillesArcas/PythonSed#7]
My data is :
192.168.0.0/24
the sed expressions is to convert from decimal to binary.  

s/\<0\>/00000000/g
s/\<1\>/00000001/g
.......
s/\<255\>/11111111/g

this works fine on everything except for the /24.  if there is no space it won't convert if there is a space it then it will convert the 24.  this works fine with native sed.  

so the data becomes,
11000000.10101000.00000000.00000000/24
when it should be.
11000000.10101000.00000000.00000000/00011000

**Comment by GillesArcas** [comment]
The pythonsed here does not implement word boundaries \< and \>. Perhaps you are mistaking with [Frank Schäckermann](https://github.com/fschaeck) fork  [repository](https://github.com/fschaeck/PythonSed).

**Comment by sptitzer1** [comment]
sorry about that you are correct.

**Comment by sptitzer1** [comment]
closing since it was to a different fork.
